# Generated by Django 4.1.3 on 2022-11-29 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="autor",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
