# Generated by Django 4.1 on 2022-10-17 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_livro_capa_alter_livro_isbn"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livro",
            name="isbn",
            field=models.CharField(max_length=32),
        ),
    ]
